### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by eisnstein** [FunkyStudioHQ/phoenix_pagination#7]
Hello,

I just wanted to install phoenix_pagination in a phoenix project but could not. I am a bit confused by the versions provided in the docs and here in the README.md. The hex docs say "0.7.0", in the README.md it is "0.6.0".

When I try "~> 0.7.0" I get the following error:

```
Resolving Hex dependencies...

Failed to use "phoenix_html" (version 3.2.0) because
  phoenix_ecto (version 4.4.0) requires ~> 2.14.2 or ~> 3.0
  phoenix_live_view (version 0.17.10) requires ~> 3.1
  phoenix_pagination (version 0.7.0) requires ~> 2.12
  mix.lock specifies 3.2.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

When I try "~> 0.6.0" I get the following error:

```
** (Mix) No matching version for phoenix_pagination ~> 0.6.0 (from: mix.exs) in registry

The latest version is: 0.7.0
```

The version in the master branch is "0.6.0" and phoenix_html version is "~> 3.2.0" but somehow not in the published package.

**Comment by andreapavoni** [comment]
Hi there, thank you for this issue. This package has been discontinued for various reasons, but we’ve started working on it again during the last days, at least to update and fix libraries and versioning.

As a quick workaround, you should use the github repo rather than the package version from hex.pm

**Comment by eisnstein** [comment]
Thanks, haven't thought about that.
